const MerchData = [
  {
    itemId: 'TB-01',
    itemImage: '/images/merchandisePage/item-1.png',
    itemName: 'Tote Bag Future Engineer',
    itemPrice: 'Rp. 55.000',
    itemDesc: ['Kain kanvas twill', 'Printing PDF', 'Resleting'],
    itemSize: '33 x 39 x 7 cm',
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-1.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'HD-01',
    itemImage: '/images/merchandisePage/item-2.png',
    itemName: 'Hoodie The Key Is In Our Hands',
    itemPrice: 'Rp. 140.000',
    itemDesc: ['Bahan Fleece', 'Digital Printing'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    isSub: true,
    numOfSub: 2,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-21.png',
        imagePreview: '/images/merchandisePage/itemSmol-21.png',
      },
      {
        imageId: 2,
        imageOriginal: '/images/merchandisePage/itemBig-22.png',
        imagePreview: '/images/merchandisePage/itemSmol-22.png',
      },
    ],
  },
  {
    itemId: 'KC-01',
    itemImage: '/images/merchandisePage/item-3.png',
    itemName: 'Keychain Kenali Dirimu',
    itemPrice: 'Rp. 15.000',
    itemDesc: ['Bahan 1 side UV Print', 'Acrylic'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-3.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'NB-01',
    itemImage: '/images/merchandisePage/item-4.png',
    itemName: 'Notebook Laungan Harapan',
    itemPrice: 'Rp. 40.000',
    itemDesc: ['Hard Cover', 'Ukuran A6', '75 Halaman'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-4.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'TP-01',
    itemImage: '/images/merchandisePage/item-5.png',
    itemName: 'Topi Iso Turu Sangar',
    itemPrice: 'Rp. 45.000',
    itemDesc: ['Bahan Twill', 'Logo Digital Bordir'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-5.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'TB-02',
    itemImage: '/images/merchandisePage/item-6.png',
    itemName: 'Tote BagMager',
    itemPrice: 'Rp. 55.000',
    itemDesc: ['Kain kanvas twill', 'Printing DTF', 'Resleting'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    itemSize: '33 x 39 x 7 cm',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-6.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'TS-02',
    itemImage: '/images/merchandisePage/item-7.png',
    itemName: 'T-Shirt White',
    itemPrice: 'Rp. 85.000',
    itemDesc: ['Bahan Cotton Combed 24s', 'Digital Printing'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    isSub: true,
    numOfSub: 3,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-71.png',
        imagePreview: '/images/merchandisePage/itemSmol-71.png',
      },
      {
        imageId: 2,
        imageOriginal: '/images/merchandisePage/itemBig-72.png',
        imagePreview: '/images/merchandisePage/itemSmol-72.png',
      },
      {
        imageId: 3,
        imageOriginal: '/images/merchandisePage/itemBig-73.png',
        imagePreview: '/images/merchandisePage/itemSmol-73.png',
      },
    ],
  },
  {
    itemId: 'TP-01',
    itemImage: '/images/merchandisePage/item-8.png',
    itemName: 'Topi Campus of Heroes',
    itemPrice: 'Rp. 45.000',
    itemDesc: ['Bahan twill', 'Logo Digital Bordir'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    itemSize: '',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-8.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'KC-02',
    itemImage: '/images/merchandisePage/item-9.png',
    itemName: 'Keychain ID Card',
    itemPrice: 'Rp. 15.000',
    itemDesc: ['Bahan 1 side UV Print', 'Acrylic'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    itemSize: '',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-9.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'TS-01',
    itemImage: '/images/merchandisePage/item-10.png',
    itemName: 'T-Shirt Black',
    itemPrice: 'Rp. 85.000',
    itemDesc: ['Bahan Cotton Combed 24s', 'Digital Printing'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    isSub: true,
    numOfSub: 3,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-101.png',
        imagePreview: '/images/merchandisePage/itemSmol-101.png',
      },
      {
        imageId: 2,
        imageOriginal: '/images/merchandisePage/itemBig-102.png',
        imagePreview: '/images/merchandisePage/itemSmol-102.png',
      },
      {
        imageId: 3,
        imageOriginal: '/images/merchandisePage/itemBig-103.png',
        imagePreview: '/images/merchandisePage/itemSmol-103.png',
      },
    ],
  },
  {
    itemId: 'LY-01',
    itemImage: '/images/merchandisePage/item-11.png',
    itemName: 'Lanyard Laungan Harapan',
    itemPrice: 'Rp. 15.000',
    itemDesc: [
      'Bahan Tali Tisu',
      'Pengait Besi',
      'Panjang Tali 90 cm',
      'Lebar Tali 2 cm',
      'Stopper Hitam',
    ],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    itemSize: '',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-11.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'KC-03',
    itemImage: '/images/merchandisePage/item-12.png',
    itemName: 'Keychain Almet on Fit',
    itemPrice: 'Rp. 15.000',
    itemDesc: ['Bahan 1 side UV Print', 'Acrylic'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    itemSize: '',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-12.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'GL-01',
    itemImage: '/images/merchandisePage/item-13.png',
    itemName: 'Gelang Shoot Your Star',
    itemPrice: 'Rp. 15.000',
    itemDesc: ['Bahan Rubber, Rubber Painting'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    itemSize: '',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-13.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'ST-01',
    itemImage: '/images/merchandisePage/item-14.png',
    itemName: 'Sticker Pack',
    itemPrice: 'Rp. 15.000',
    itemDesc: ['Bahan Vinyl Glossy'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    itemSize: '',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-14.png',
        imagePreview: '',
      },
    ],
  },
  {
    itemId: 'KP-01',
    itemImage: '/images/merchandisePage/item-15.png',
    itemName: 'Kipas Ini Lho ITS',
    itemPrice: 'Rp. 10.000',
    itemDesc: ['Bahan Kertas Laminasi Glossy', 'Ukuran: 15 cm'],
    itemLink: 'https://linktr.ee/MerchandiseILITS2023',
    itemOngkir: '#2',
    itemSize: '',
    isSub: false,
    itemSubImage: [
      {
        imageId: 1,
        imageOriginal: '/images/merchandisePage/itemBig-15.png',
        imagePreview: '',
      },
    ],
  },
];

export default MerchData;
